name: CI

on:
  pull_request:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Run tests and lint
        run: pnpm lint && pnpm test
    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile --production --ignore-scripts
      - name: Build application
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: optimax-dev-test-task
          channelId: live
      - name: Clean build directory
        run: rm -Rf ./dist/

    


      