name: Deploy storybook

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install tools from asdf config
        uses: ai/asdf-cache-action@v1
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
     
      - name: Build
        run: pnpm storybook:build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './storybook-static'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: storybook-static
          CLEAN: true
